package com.applicate.enrichment;

import com.applicate.services.channelkart.services.ServiceLocator;
import com.salescode.dim.etl.enrichment.AbstractEnrichment;
import com.salescode.dim.jooq.generated.tables.pojos.HierarchyMetadata;
import com.salescode.dim.jooq.impl.OutletDetails;
import java.util.List;
import com.applicate.services.channelkart.services.SequenceInfoService;
import com.applicate.services.channelkart.utils.StringUtils;
import com.salescode.dim.etl.OperationResult;
import com.salescode.dim.jooq.impl.SequenceInfo;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class VistaarOutletCodeAutoGeneratedEnrichment extends AbstractEnrichment<OutletDetails> {

	private static final Logger logger = LoggerFactory.getLogger(VistaarOutletCodeAutoGeneratedEnrichment.class);

	private SequenceInfoService service = (SequenceInfoService) ServiceLocator.lookup(SequenceInfo.class);

	private static final String OUTLET_DETAILS = "OutletDetails";
	private static final String OUTLET_ENTITY_NAME = "com.applicate.services.channelkart.models.OutletDetails";

	@Override
	public OperationResult.StepResult apply(OutletDetails cdm) {
		if (StringUtils.isNotBlank(cdm.getOutletcode()) && !"auto_generated".equalsIgnoreCase(cdm.getOutletcode().trim())) {
			return new OperationResult.StepResult(OperationResult.Status.OK, "Data enrichment skipped due to already existing outletcode");
		}

		String immediateParentLoginId = getImmediateParentInfo(cdm);
		if (!StringUtils.isNotBlank(immediateParentLoginId)) {
			return new OperationResult.StepResult(OperationResult.Status.ERROR, "Immediate parent not found for the outlet");
		}

		if (cdm.getOutletType().equalsIgnoreCase("stockist")) {
			cdm.setOutletcode(immediateParentLoginId);
		} else if (service.shouldEnableSequenceGenerator(OUTLET_DETAILS, "outletCode", cdm.getOutletcode())) {
			try {
				int sequence = service.getSequenceNumber(OUTLET_ENTITY_NAME, "outletCode");
				String generatedCode = "VISOUT" + String.format("%07d", sequence);
				cdm.setOutletcode(generatedCode);
			} catch (Exception e) {
				logger.error("Exception occur in OutletCode Generation :", e);
				return new OperationResult.StepResult(OperationResult.Status.ERROR, e.getLocalizedMessage());
			}
		} else {
			return new OperationResult.StepResult(OperationResult.Status.ERROR, "Unable to generate the outlet code");
		}
		return new OperationResult.StepResult(OperationResult.Status.OK, "Data enriched successfully");
	}

	private String getImmediateParentInfo(OutletDetails cdm) {
		String result = null;
		List<HierarchyMetadata> listOfParents = cdm.getImmediateParent();
		if (listOfParents != null && !listOfParents.isEmpty()) {
			result = listOfParents.get(0).getParent();
		}
		return result;
	}

}